#ifndef CF_UI_LAYOUT_H
#define CF_UI_LAYOUT_H

/* Canonical 320x200 retail layout. Keep input and rendering in sync. */
#define CF_UI_SCREEN_W 320
#define CF_UI_SCREEN_H 200

#define CF_UI_HEADER_X 0
#define CF_UI_HEADER_Y 0
#define CF_UI_HEADER_W CF_UI_SCREEN_W
#define CF_UI_HEADER_H 21

#define CF_UI_BOARD_X 18
#define CF_UI_BOARD_Y 27
#define CF_UI_SQUARE_SIZE 18
#define CF_UI_BOARD_PIXELS (CF_UI_SQUARE_SIZE * 8)

#define CF_UI_BOARD_FRAME_X 14
#define CF_UI_BOARD_FRAME_Y 23
#define CF_UI_BOARD_FRAME_W 152
#define CF_UI_BOARD_FRAME_H 154

#define CF_UI_PANEL_X 170
#define CF_UI_PANEL_Y 24
#define CF_UI_PANEL_W 143
#define CF_UI_PANEL_H 151
#define CF_UI_PANEL_INSET 10
#define CF_UI_PANEL_CONTENT_X (CF_UI_PANEL_X + CF_UI_PANEL_INSET)
#define CF_UI_PANEL_CONTENT_W 123

#define CF_UI_COMMAND_X 0
#define CF_UI_COMMAND_Y 181
#define CF_UI_COMMAND_W CF_UI_SCREEN_W
#define CF_UI_COMMAND_H 19

/* Build 13.5 normal gameplay HUD positions. */
#define CF_UI_HEADER_TITLE_X 10
#define CF_UI_HEADER_TITLE_Y 5
#define CF_UI_HEADER_TAGLINE_X 165
#define CF_UI_HEADER_TAGLINE_Y 5
#define CF_UI_HEADER_RULE_Y 16

#define CF_UI_HUD_LABEL_X CF_UI_PANEL_CONTENT_X
#define CF_UI_HUD_VALUE_X 223
#define CF_UI_HUD_DIVIDER_W CF_UI_PANEL_CONTENT_W
#define CF_UI_HUD_TURN_Y 31
#define CF_UI_HUD_STATE_Y 42
#define CF_UI_HUD_DIVIDER1_Y 52
#define CF_UI_HUD_PIECE_LABEL_Y 58
#define CF_UI_HUD_PIECE_BOX_X 181
#define CF_UI_HUD_PIECE_BOX_Y 68
#define CF_UI_HUD_PIECE_BOX_W 22
#define CF_UI_HUD_PIECE_BOX_H 22
#define CF_UI_HUD_PIECE_TEXT_X 208
#define CF_UI_HUD_PIECE_NAME_Y 69
#define CF_UI_HUD_PIECE_SQUARE_Y 80
#define CF_UI_HUD_DIVIDER2_Y 94
#define CF_UI_HUD_GAS_LABEL_Y 99
#define CF_UI_HUD_GAS_PIPS_Y 110
#define CF_UI_HUD_DIVIDER3_Y 121
#define CF_UI_HUD_CPU_Y 127
#define CF_UI_HUD_DIVIDER4_Y 139
#define CF_UI_HUD_ACTION_LABEL_Y 144
#define CF_UI_HUD_ACTION_LINE1_Y 155
#define CF_UI_HUD_ACTION_LINE2_Y 165

#define CF_UI_PROMPT_TEXT_Y 187
#define CF_UI_PROMPT_TURN_X 8
#define CF_UI_PROMPT_FART_X 96
#define CF_UI_PROMPT_SAVE_X 137
#define CF_UI_PROMPT_LOAD_X 178
#define CF_UI_PROMPT_HELP_X 219
#define CF_UI_PROMPT_ESC_X 260

/* Build 13.6 Fart-mode presentation positions. */
#define CF_UI_FART_HEADER_TAGLINE_X 112
#define CF_UI_FART_HEADER_PUFF_X 224
#define CF_UI_FART_HEADER_PUFF_Y 1
#define CF_UI_FART_BADGE_X 246
#define CF_UI_FART_BADGE_Y 3
#define CF_UI_FART_BADGE_W 66
#define CF_UI_FART_BADGE_H 12
#define CF_UI_FART_BADGE_TEXT_X 255
#define CF_UI_FART_BADGE_TEXT_Y 5

#define CF_UI_FART_SOURCE_LABEL_Y 53
#define CF_UI_FART_PIECE_BOX_X 181
#define CF_UI_FART_PIECE_BOX_Y 61
#define CF_UI_FART_PIECE_BOX_W 20
#define CF_UI_FART_PIECE_BOX_H 20
#define CF_UI_FART_PIECE_TEXT_X 205
#define CF_UI_FART_PIECE_NAME_Y 62
#define CF_UI_FART_PIECE_SQUARE_Y 73
#define CF_UI_FART_GAS_LABEL_Y 84
#define CF_UI_FART_GAS_PIPS_Y 93
#define CF_UI_FART_DIRECTION_Y 104
#define CF_UI_FART_DIRECTION_VALUE_X 247
#define CF_UI_FART_PREVIEW_LABEL_Y 114
#define CF_UI_FART_PREVIEW_LINE1_Y 123
#define CF_UI_FART_PREVIEW_LINE2_Y 132
#define CF_UI_FART_CPU_Y 141
#define CF_UI_FART_LAST_DIVIDER_Y 149
#define CF_UI_FART_ACTION_LABEL_Y 151
#define CF_UI_FART_ACTION_LINE1_Y 159
#define CF_UI_FART_ACTION_LINE2_Y 167

#define CF_UI_FART_PROMPT_ARROWS_X 8
#define CF_UI_FART_PROMPT_ENTER_X 157
#define CF_UI_FART_PROMPT_ESC_X 247

#endif
