#!/usr/bin/env python3
"""Build the Chess Fart compact bitmap font from its indexed PNG atlas."""

from __future__ import print_function

import argparse
import os
import sys

import build_assets

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE_PATH = os.path.join(ROOT, "assets_src", "ui", "font_body.png")
GENERATED_PATH = os.path.join(ROOT, "src", "generated", "font_generated.inc")
REPORT_PATH = os.path.join(ROOT, "build", "assets", "FONT_REPORT.txt")

ATLAS_W = 128
ATLAS_H = 32
CELL_W = 8
CELL_H = 8
FIRST_CHAR = 32
GLYPH_COUNT = 64
RUNTIME_BYTES = (ATLAS_W * ATLAS_H) // 8


def build_font():
    png = build_assets.read_indexed_png(SOURCE_PATH)
    if png["width"] != ATLAS_W or png["height"] != ATLAS_H:
        raise build_assets.AssetError(
            "font atlas is %dx%d, expected %dx%d" %
            (png["width"], png["height"], ATLAS_W, ATLAS_H))
    transparency = png["transparency"]
    if transparency is None or len(transparency) < 1 or transparency[0] != 0:
        raise build_assets.AssetError(
            "font atlas must make palette index 0 transparent")
    pixels = []
    for row in png["rows"]:
        pixels.extend(row)
    if any(value not in (0, 1) for value in pixels):
        raise build_assets.AssetError(
            "font atlas may only use semantic indices 0 and 1")
    packed = build_assets._pack_pixels("bit", pixels)
    if len(packed) != RUNTIME_BYTES:
        raise build_assets.AssetError(
            "font atlas packed to %d bytes, expected %d" %
            (len(packed), RUNTIME_BYTES))
    return packed, png["sha256"]


def render_include(packed):
    lines = [
        "/* Auto-generated by tools/build_font.py. DO NOT EDIT. */",
        "/* 8x8 cells, ASCII 32..95, transparent index 0. */",
        "",
        "#define CF_FONT_ATLAS_W %d" % ATLAS_W,
        "#define CF_FONT_ATLAS_H %d" % ATLAS_H,
        "#define CF_FONT_CELL_W %d" % CELL_W,
        "#define CF_FONT_CELL_H %d" % CELL_H,
        "#define CF_FONT_FIRST_CHAR %d" % FIRST_CHAR,
        "#define CF_FONT_GLYPH_COUNT %d" % GLYPH_COUNT,
        "#define CF_FONT_RUNTIME_BYTES %dU" % RUNTIME_BYTES,
        "",
        "static const cf_u8 cf_font_bitmap[%d] = {" % RUNTIME_BYTES,
    ]
    for row in range(0, len(packed), 16):
        values = packed[row:row + 16]
        lines.append("    " + ", ".join(
            "0x%02X" % value for value in values) + ",")
    lines.append("};")
    lines.append("")
    return "\n".join(lines).encode("ascii")


def write_report(sha256):
    directory = os.path.dirname(REPORT_PATH)
    if not os.path.isdir(directory):
        os.makedirs(directory)
    lines = [
        "Chess Fart Build 13 bitmap font report",
        "atlas=%dx%d" % (ATLAS_W, ATLAS_H),
        "cell=%dx%d" % (CELL_W, CELL_H),
        "first_char=%d" % FIRST_CHAR,
        "glyphs=%d" % GLYPH_COUNT,
        "packed_runtime_bytes=%d" % RUNTIME_BYTES,
        "source=assets_src/ui/font_body.png sha256=%s" % sha256,
    ]
    with open(REPORT_PATH, "w") as handle:
        handle.write("\n".join(lines) + "\n")


def main():
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()

    try:
        packed, sha256 = build_font()
        rendered = render_include(packed)
        if args.write:
            directory = os.path.dirname(GENERATED_PATH)
            if not os.path.isdir(directory):
                os.makedirs(directory)
            with open(GENERATED_PATH, "wb") as handle:
                handle.write(rendered)
        else:
            try:
                with open(GENERATED_PATH, "rb") as handle:
                    current = handle.read()
            except IOError:
                raise build_assets.AssetError(
                    "generated font include is missing; run --write")
            if current != rendered:
                raise build_assets.AssetError(
                    "generated font include is stale; run tools/build_font.py --write")
        write_report(sha256)
    except build_assets.AssetError as exc:
        print("FONT ASSET ERROR: %s" % exc, file=sys.stderr)
        return 1

    print("Build 13 font OK: %d glyphs, %d packed runtime bytes" %
          (GLYPH_COUNT, RUNTIME_BYTES))
    return 0


if __name__ == "__main__":
    sys.exit(main())
